services:
  validator:
    build:
      context: .
    image: astridintelligence/astrid-validator
    environment:
      NODE_ENV: production
    env_file:
      - .env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
